"""
1st Workflow Plugin.

This workflow was auto-generated by Hythera Console.
Based on SumDotPipeline example (Sum → Dot pipeline).

Module path:  nos.plugins.workflows.dev_.test_wf_01
Class name:   TestWf01
Workflow ID:  test_wf_01

To register this workflow after editing:
    reg workflow test_wf_01 TestWf01 nos.plugins.workflows.dev_.test_wf_01

To execute this workflow:
    run workflow db test_wf_01 --sync --debug
"""

from pydantic import BaseModel, Field

from nos.core.engine.base import Workflow, Node, NodeOutput, AlwaysLink


# --- State schema (shared workflow state) ---
class TestWf01State(BaseModel):
    """State for 1st pipeline."""

    a: float = Field(default=0, description="First number for sum")
    b: float = Field(default=0, description="Second number for sum")
    sum_result: float = Field(default=0, description="Result from SimpleSumNode")
    vec_a: list = Field(default_factory=lambda: [1, 0], description="First vector for dot")
    vec_b: list = Field(default_factory=lambda: [0, 1], description="Second vector for dot")
    dot_result: float = Field(default=0, description="Result from SimpleDotNode")


# --- Inline nodes (replace with plugins as needed) ---
class SimpleSumNode(Node):
    """Sums a and b from state, writes result to state['sum_result']."""

    def _do_execute(self, state: dict, params_dict: dict) -> NodeOutput:
        a = state.get("a", 0)
        b = state.get("b", 0)
        result = a + b
        state["sum_result"] = result
        return NodeOutput(output=dict(result=result))


class SimpleDotNode(Node):
    """Dot product of vec_a and vec_b from state, writes to state['dot_result']."""

    def _do_execute(self, state: dict, params_dict: dict) -> NodeOutput:
        va = state.get("vec_a", [1, 0])
        vb = state.get("vec_b", [0, 1])
        result = sum(x * y for x, y in zip(va, vb))
        state["dot_result"] = result
        return NodeOutput(output=dict(result=result))


# --- Workflow ---
class TestWf01(Workflow):
    """Simple pipeline: Sum → Dot. Uses shared state to pass data between nodes."""

    workflow_id = "test_wf_01"
    name = "1st"

    @property
    def state_schema(self):
        return TestWf01State

    def define(self):
        # Create nodes
        sum_node = SimpleSumNode(node_id="sum", name="Sum")
        dot_node = SimpleDotNode(node_id="dot", name="Dot")

        # Add nodes
        self.add_node(sum_node)
        self.add_node(dot_node)

        # Link: sum → dot (AlwaysLink = unconditional)
        link = AlwaysLink(
            link_id="sum_to_dot",
            from_node_id="sum",
            to_node_id="dot",
            name="Sum → Dot",
        )
        self.add_link(link)

        # Entry point
        self.set_entry_node("sum")
