"""
Plugin Code Service.

Provides reusable functions for creating and saving node/workflow code files.
Can be called from both REST API and Socket.IO handlers.

**Scaffold / pip flows:** prefer :mod:`nos.platform.services.plugin_scaffold_service` for
``plugin create`` / ``plugin install`` and package layout; path mapping helpers here remain
for editor open/save resolution.
"""

import os
import logging
from typing import Tuple, Optional
from dataclasses import dataclass
from datetime import datetime

logger = logging.getLogger(__name__)


@dataclass
class SaveCodeResult:
    """Result of a save/create code operation."""
    success: bool
    message: str
    file_path: Optional[str] = None
    content: Optional[str] = None
    registration_status: Optional[str] = None
    registration_error: Optional[str] = None


# =============================================================================
# Node Templates
# =============================================================================

NODE_TEMPLATE = '''"""
{name} Node Plugin.

This node was auto-generated by Hythera Console.
Edit this file to implement your custom logic.

Module path: {module_path}
Class name:  {class_name}
Node ID:     {node_id}

To test without registering (direct execution):
    run node dev {module_path} {class_name} --sync --debug

To register this node after editing:
    reg node {node_id} {class_name} {module_path}

To execute this node (after registration):
    run node db {node_id} --sync --debug
"""

from nos.core.engine.base import Node, NodeOutput


class {class_name}(Node):
    """
    {name} - Hythera Node Plugin.
    
    A node receives input parameters, processes them, and returns output.
    The execution channel provides real-time logging capabilities.
    
    Lifecycle:
        1. __init__: Initialize node with ID and name
        2. _do_execute: Main logic - receives state and params, returns NodeOutput
    
    Available via self.exec_log (platform EventLog):
        - self.exec_log.log("info", message)   # Log a message (levels: debug, info, warning, error)
        - self.exec_log.log("info", "msg", event="my.step", key=value)  # event type + extra fields
        - self.exec_log.log("info", "msg", key=value)  # omit event → default "Logging event" (CustomEvent)
        - self.request_and_wait(event_type, data)     # Client round-trip; None on failure
        - self.request_and_wait_result(...)           # Same, structured ok/status/detail/response
    """
    
    def __init__(self, node_id: str = "{node_id}", name: str = None):
        """
        Initialize the node.
        
        Args:
            node_id: Unique identifier for this node (used in workflows and DB)
            name: Human-readable display name
        """
        super().__init__(node_id, name or "{name}")
    
    def _do_execute(self, state_dict: dict, params_dict: dict) -> NodeOutput:
        """
        Execute the node logic.
        
        This is the main method to implement. It receives the current state
        and input parameters, and should return a NodeOutput with results.
        
        Args:
            state_dict: Current workflow state (shared across nodes in a workflow)
                        Example: {{"previous_result": 42, "user_id": "abc123"}}
            params_dict: Input parameters for this specific execution
                         Example: {{"input_value": 10, "operation": "multiply"}}
        
        Returns:
            NodeOutput: Contains output data and optional metadata
                - output: The result data (dict, list, or any JSON-serializable value)
                - metadata: Optional execution metadata (timing, stats, etc.)
        
        Example usage of channel logging:
            self.exec_log.log("info", "Starting processing...")
            self.exec_log.log("debug", f"Received params: {{params_dict}}")
            self.exec_log.log("info", "Status update", status="processing")
        """
        # -----------------------------------------------------------------
        # YOUR LOGIC HERE
        # -----------------------------------------------------------------
        
        # Example: Log execution start
        self.exec_log.log("info", "Node execution started")
        
        # Example: Access input parameters
        # input_value = params_dict.get("input_value", 0)
        
        # Example: Access shared state from previous nodes
        # previous_result = state_dict.get("previous_result")
        
        # Example: Log with extra data
        # self.exec_log.log("info", "Processing complete", result=computed_value)
        
        # Example: Request user input (only works with --debug mode)
        # response = self.request_and_wait("confirmation_required", {{
        #     "title": "Continue?",
        #     "message": "Do you want to proceed?"
        # }})
        
        # Build result
        result = {{
            "status": "success",
            "message": "{name} executed successfully",
            "input_params": params_dict,
        }}
        
        # Log completion
        self.exec_log.log("info", "Node execution completed")
        
        # Return output
        return NodeOutput(
            output=result,
            metadata={{
                "executed_by": "{class_name}",
                "node_id": "{node_id}"
            }}
        )
'''


# =============================================================================
# Workflow Templates
# =============================================================================

WORKFLOW_TEMPLATE = '''"""
{name} Workflow Plugin.

This workflow was auto-generated by Hythera Console.
Based on SumDotPipeline example (Sum → Dot pipeline).

Module path:  {module_path}
Class name:   {class_name}
Workflow ID:  {workflow_id}

To test without registering (direct execution):
    run workflow direct {module_path} {class_name} --sync --debug

To register this workflow after editing:
    reg workflow {workflow_id} {class_name} {module_path}

To execute this workflow (after registration):
    run workflow db {workflow_id} --sync --debug
"""

from pydantic import BaseModel, Field

from ....base import Workflow, Node, NodeOutput, AlwaysLink


# --- State schema (shared workflow state) ---
class {class_name}State(BaseModel):
    """State for {name} pipeline."""

    a: float = Field(default=0, description="First number for sum")
    b: float = Field(default=0, description="Second number for sum")
    sum_result: float = Field(default=0, description="Result from SimpleSumNode")
    vec_a: list = Field(default_factory=lambda: [1, 0], description="First vector for dot")
    vec_b: list = Field(default_factory=lambda: [0, 1], description="Second vector for dot")
    dot_result: float = Field(default=0, description="Result from SimpleDotNode")


# --- Inline nodes (replace with plugins as needed) ---
class SimpleSumNode(Node):
    """Sums a and b from state, writes result to state['sum_result']."""

    def _do_execute(self, state: dict, params_dict: dict) -> NodeOutput:
        a = state.get("a", 0)
        b = state.get("b", 0)
        result = a + b
        state["sum_result"] = result
        return NodeOutput(output=dict(result=result))


class SimpleDotNode(Node):
    """Dot product of vec_a and vec_b from state, writes to state['dot_result']."""

    def _do_execute(self, state: dict, params_dict: dict) -> NodeOutput:
        va = state.get("vec_a", [1, 0])
        vb = state.get("vec_b", [0, 1])
        result = sum(x * y for x, y in zip(va, vb))
        state["dot_result"] = result
        return NodeOutput(output=dict(result=result))


# --- Workflow ---
class {class_name}(Workflow):
    """Simple pipeline: Sum → Dot. Uses shared state to pass data between nodes."""

    workflow_id = "{workflow_id}"
    name = "{name}"

    @property
    def state_schema(self):
        return {class_name}State

    def define(self):
        # Create nodes
        sum_node = SimpleSumNode(node_id="sum", name="Sum")
        dot_node = SimpleDotNode(node_id="dot", name="Dot")

        # Add nodes
        self.add_node(sum_node)
        self.add_node(dot_node)

        # Link: sum → dot (AlwaysLink = unconditional)
        link = AlwaysLink(
            link_id="sum_to_dot",
            from_node_id="sum",
            to_node_id="dot",
            name="Sum → Dot",
        )
        self.add_link(link)

        # Entry point
        self.set_entry_node("sum")
'''


# =============================================================================
# Path Resolution
# =============================================================================

PLUGIN_BASE = "nos.plugins"


def _module_path_for_import(module_path: str) -> str:
    """
    Dotted module path for ``importlib.import_module`` / ``Node.load(dev)`` / ``Workflow.load(dev)``.

    Plugin code under ``PLUGIN_PATH`` is imported as a **normal** top-level package (e.g.
    ``my_pkg.node_plugin``). Nothing is rewritten to ``nos.plugins.nodes.*``.
    """
    if not module_path or not isinstance(module_path, str):
        return (module_path or "").strip()
    raw = module_path.strip()
    if raw.startswith("ext:"):
        return raw[4:].strip()
    return raw


def _normalize_plugin_module_path(module_path: str, plugin_type: Optional[str] = None) -> str:
    """
    Normalize **only** for mapping module paths to files under ``PLUGIN_PATH`` (open/save/create).

    - Paths starting with ``nos.`` — unchanged (virtual explorer tree).
    - ``nodes....`` (node) — prefix ``nos.plugins.`` so ``nodes.dev.foo`` → ``nos.plugins.nodes.dev.foo``.
    - ``workflows....`` / ``old....`` (workflow) — prefix ``nos.plugins.``.
    - Anything else — returned as-is (external package dotted path, e.g. ``my_pkg.node_plugin``).

    For **run node dev** / **run workflow dev**, use :func:`_module_path_for_import` instead.
    """
    if not module_path or not isinstance(module_path, str):
        return (module_path or "").strip()
    raw = module_path.strip()
    if raw.startswith("ext:"):
        return raw[4:].strip()
    if raw.startswith("nos."):
        return raw
    if plugin_type == "node" and raw.startswith("nodes."):
        return f"{PLUGIN_BASE}.{raw}"
    if plugin_type == "workflow" and (raw.startswith("workflows.") or raw.startswith("old.")):
        return f"{PLUGIN_BASE}.{raw}"
    return raw


def _resolve_external_plugin_py(module_path: str) -> Tuple[Optional[str], Optional[str]]:
    """
    Map a **non-nos.** dotted path (external pip package under ``PLUGIN_PATH``) to a ``.py`` file.

    Layout: ``<PLUGIN_PATH>/<dist>/src/<pkg>/.../<module>.py`` (same as ``plugin create`` scaffold).
    """
    raw = (module_path or "").strip()
    if raw.startswith("ext:"):
        raw = raw[4:].strip()
    if not raw or raw.startswith("nos."):
        return None, None
    parts = [p for p in raw.split(".") if p]
    if len(parts) < 2:
        return None, None
    try:
        from nos.platform.config.paths import get_plugin_path
        from nos.platform.plugins.scaffold import _parse_slug

        _pkg, dist = _parse_slug(parts[0])
        plugin_root = get_plugin_path().resolve()
    except ValueError:
        return None, None

    base = plugin_root / dist / "src" / _pkg
    if len(parts) == 2:
        py = base / f"{parts[1]}.py"
    else:
        py = base.joinpath(*parts[1:-1]) / f"{parts[-1]}.py"
    try:
        py = py.resolve()
        py.relative_to(plugin_root)
    except ValueError:
        return None, None
    dev_root_real = os.path.realpath(str(plugin_root))
    alt = os.path.realpath(str(py))
    if not alt.startswith(dev_root_real + os.sep) and alt != dev_root_real:
        return None, None
    if not alt.endswith(".py"):
        return None, None
    return alt, dev_root_real


def _get_nos_pkg_dir() -> Optional[str]:
    """Get the nos package directory."""
    try:
        import nos
        return os.path.dirname(os.path.abspath(nos.__file__))
    except Exception:
        return None


def _plugin_dev_root() -> Optional[str]:
    """
    Engine «Plugins explorer» root: ``PLUGIN_PATH`` (see ``nos.platform.config.paths``), default
    ``~/.nos/plugins``. Same logical path as ``nos.platform.api.console.routes._get_plugin_dev_root``
    (no mkdir here).
    """
    try:
        from nos.platform.config.paths import get_plugin_path

        p = str(get_plugin_path().resolve())
    except ValueError:
        return None
    return p if os.path.isdir(p) else None


def resolve_node_path(module_path: str) -> Tuple[Optional[str], Optional[str]]:
    """
    Map ``nos.plugins.<...>`` (virtual tree) **or** an external package path (``pkg.sub.module``)
    to a ``.py`` under ``PLUGIN_PATH``.
    """
    path = _normalize_plugin_module_path(module_path or "", "node")
    parts = path.split(".")
    if not parts or parts[0] != "nos":
        return _resolve_external_plugin_py(module_path or "")

    rel_parts = parts[1:]
    if not rel_parts or rel_parts[0] != "plugins":
        return None, None

    dev_root = _plugin_dev_root()
    if not dev_root or len(rel_parts) < 2:
        return None, None

    sub = [p for p in rel_parts[1:] if p and p not in (".", "..")]
    if not sub:
        return None, None

    dev_root_real = os.path.realpath(dev_root)
    alt = os.path.realpath(os.path.join(dev_root_real, *sub) + ".py")
    if not alt.startswith(dev_root_real + os.sep):
        return None, None

    return alt, dev_root_real


def resolve_workflow_path(module_path: str) -> Tuple[Optional[str], Optional[str]]:
    """
    Resolve ``nos.plugins.workflows...`` / ``nos.plugins.old...`` or generic ``nos.plugins...``
    trees under ``PLUGIN_PATH``, or an external package path (``pkg.workflow_plugin``).
    """
    path = _normalize_plugin_module_path(module_path or "", "workflow")
    parts = path.split(".")
    if not parts or parts[0] != "nos":
        return _resolve_external_plugin_py(module_path or "")

    rel_parts = parts[1:]
    if not rel_parts or rel_parts[0] != "plugins":
        return None, None

    dev_root = _plugin_dev_root()
    if not dev_root or len(rel_parts) < 2:
        return None, None

    sub = rel_parts[1:]
    alt = os.path.realpath(os.path.join(dev_root, *sub) + ".py")
    allowed_wf = os.path.realpath(os.path.join(dev_root, "workflows"))
    allowed_old = os.path.realpath(os.path.join(dev_root, "old"))
    if sub and sub[0] == "workflows" and (alt.startswith(allowed_wf + os.sep) or alt == allowed_wf):
        return alt, allowed_wf
    if sub and sub[0] == "old" and (alt.startswith(allowed_old + os.sep) or alt == allowed_old):
        return alt, allowed_old

    return resolve_node_path(path)


def _ensure_package_init(allowed_dir: str, target_dir: str) -> None:
    """Ensure every directory from allowed_dir to target_dir has __init__.py."""
    allowed_real = os.path.realpath(allowed_dir)
    current = os.path.realpath(target_dir)
    
    if not current.startswith(allowed_real + os.sep) and current != allowed_real:
        return
    
    to_create = []
    while current and current != allowed_real and current != os.path.dirname(current):
        init_path = os.path.join(current, "__init__.py")
        if not os.path.isfile(init_path):
            to_create.append(init_path)
        current = os.path.dirname(current)
    
    for init_path in to_create:
        with open(init_path, "w", encoding="utf-8") as f:
            f.write("")


# =============================================================================
# Read Operations
# =============================================================================

def read_node_code(
    node_id: str = None,
    module_path: str = None
) -> SaveCodeResult:
    """
    Read node plugin file content directly from file system.
    
    Does NOT require DB registration - works with any file under nodes directory.
    
    Args:
        node_id: Node identifier (used with module_path for context, not for path resolution)
        module_path: Full module path (REQUIRED) - e.g., nos.plugins.nodes.my_folder.my_node
        
    Returns:
        SaveCodeResult with content and file_path
    """
    # module_path is required - no default folder
    if not module_path:
        return SaveCodeResult(
            success=False,
            message="module_path is required (e.g., nos.plugins.nodes.<folder>.<module_name>)"
        )
    
    actual_module_path = module_path
    
    # Resolve to file path
    file_path, _ = resolve_node_path(actual_module_path)
    if not file_path:
        return SaveCodeResult(
            success=False,
            message=f"Invalid module_path: {actual_module_path}"
        )
    
    # Check if file exists
    if not os.path.exists(file_path):
        return SaveCodeResult(
            success=False,
            message=f"File not found: {file_path}"
        )
    
    # Read content
    try:
        with open(file_path, "r", encoding="utf-8") as f:
            content = f.read()
    except OSError as e:
        logger.error(f"read_node_code: read failed: {e}")
        return SaveCodeResult(
            success=False,
            message=f"Read error: {str(e)}"
        )
    
    return SaveCodeResult(
        success=True,
        message=f"Node code loaded from: {file_path}",
        file_path=file_path,
        content=content
    )


def read_workflow_code(
    workflow_id: str = None,
    module_path: str = None
) -> SaveCodeResult:
    """
    Read workflow plugin file content directly from file system.
    
    Does NOT require DB registration - works with any file under workflows directory.
    
    Args:
        workflow_id: Workflow identifier (used with module_path for context, not for path resolution)
        module_path: Full module path (REQUIRED) - e.g., nos.plugins.workflows.my_folder.my_workflow
        
    Returns:
        SaveCodeResult with content and file_path
    """
    # module_path is required - no default folder
    if not module_path:
        return SaveCodeResult(
            success=False,
            message="module_path is required (e.g., nos.plugins.workflows.<folder>.<module_name>)"
        )
    
    actual_module_path = module_path
    
    # Resolve to file path
    file_path, _ = resolve_workflow_path(actual_module_path)
    if not file_path:
        return SaveCodeResult(
            success=False,
            message=f"Invalid module_path: {actual_module_path}"
        )
    
    # Check if file exists
    if not os.path.exists(file_path):
        return SaveCodeResult(
            success=False,
            message=f"File not found: {file_path}"
        )
    
    # Read content
    try:
        with open(file_path, "r", encoding="utf-8") as f:
            content = f.read()
    except OSError as e:
        logger.error(f"read_workflow_code: read failed: {e}")
        return SaveCodeResult(
            success=False,
            message=f"Read error: {str(e)}"
        )
    
    return SaveCodeResult(
        success=True,
        message=f"Workflow code loaded from: {file_path}",
        file_path=file_path,
        content=content
    )


# =============================================================================
# Node Operations
# =============================================================================

def create_node(
    node_id: str,
    class_name: str,
    module_path: str,
    name: Optional[str] = None
) -> SaveCodeResult:
    """
    Create a new node plugin file with template code.
    
    Args:
        node_id: Unique node identifier
        class_name: Python class name for the node
        module_path: Full or relative path (e.g. nos.plugins.nodes.dev.my_node, nodes.dev.my_node, or dev_.my_node)
        name: Display name (defaults to node_id titlecased)
        
    Returns:
        SaveCodeResult with operation status
    """
    normalized_path = _normalize_plugin_module_path(module_path or "", "node")
    # Validate and resolve path
    file_path, allowed_dir = resolve_node_path(normalized_path)
    if not file_path:
        return SaveCodeResult(
            success=False,
            message="Invalid module_path (must map under plugin dev root, see PLUGIN_PATH / ~/.nos/plugins)",
        )
    
    # Check if file already exists
    if os.path.exists(file_path):
        return SaveCodeResult(
            success=False,
            message=f"File already exists: {file_path}"
        )
    
    # Generate name if not provided
    if not name:
        name = node_id.replace("_", " ").title()
    
    # Generate content from template (use normalized path for reg command)
    content = NODE_TEMPLATE.format(
        node_id=node_id,
        class_name=class_name,
        module_path=normalized_path,
        name=name
    )
    
    # Save the file and create DB record
    return save_node_code(node_id, class_name, normalized_path, content, name=name, is_create=True)


def save_node_code(
    node_id: str,
    class_name: str,
    module_path: str,
    content: str,
    name: Optional[str] = None,
    is_create: bool = False,
) -> SaveCodeResult:
    """
    Save node code to file only (no DB record - use register_node for that).
    
    Args:
        node_id: Node identifier
        class_name: Python class name
        module_path: Full module path
        content: Python source code
        name: Display name (defaults to node_id titlecased)
        
    Returns:
        SaveCodeResult with operation status
    """
    # Resolve path
    file_path, allowed_dir = resolve_node_path(module_path)
    if not file_path:
        return SaveCodeResult(
            success=False,
            message="Invalid module_path (must map under plugin dev root, see PLUGIN_PATH / ~/.nos/plugins)",
        )
    
    # Create directory structure and write file
    try:
        target_dir = os.path.dirname(file_path)
        os.makedirs(target_dir, exist_ok=True)
        if target_dir != allowed_dir:
            _ensure_package_init(allowed_dir, target_dir)
        
        with open(file_path, "w", encoding="utf-8") as f:
            f.write(content)
    except OSError as e:
        logger.error(f"save_node_code: write failed: {e}")
        return SaveCodeResult(
            success=False,
            message=f"Write error: {str(e)}"
        )
    
    verb = "created" if is_create else "saved"
    return SaveCodeResult(
        success=True,
        message=f"Node file {verb}: {file_path}. Use 'reg node {node_id}' to register.",
        file_path=file_path,
        content=content
    )


def write_and_register_node_code(
    node_id: str,
    class_name: str,
    module_path: str,
    content: str,
) -> SaveCodeResult:
    """
    Write node Python source to file, try to register, and update DB registration_status.
    Used by both REST API (save-code) and Socket.IO (save command).
    
    Args:
        node_id: Node identifier
        class_name: Python class name for registration
        module_path: Full module path (e.g. nos.plugins.nodes.folder.my_node)
        content: Python source code to write
        
    Returns:
        SaveCodeResult with success, message, file_path, registration_status, registration_error
    """
    from nos.core.engine.plugin_loader import try_register_node
    from .sqlalchemy.node import repository as node_repo
    from .sqlalchemy.node.model import RegistrationStatus
    
    module_path = _normalize_plugin_module_path(module_path or "", "node")
    file_path, allowed_dir = resolve_node_path(module_path)
    if not file_path:
        return SaveCodeResult(
            success=False,
            message="Invalid module_path (must map under plugin dev root, see PLUGIN_PATH / ~/.nos/plugins)",
        )
    
    try:
        target_dir = os.path.dirname(file_path)
        os.makedirs(target_dir, exist_ok=True)
        if target_dir != allowed_dir:
            _ensure_package_init(allowed_dir, target_dir)
        with open(file_path, "w", encoding="utf-8") as f:
            f.write(content)
    except OSError as e:
        logger.error(f"write_and_register_node_code: write failed: {e}")
        return SaveCodeResult(
            success=False,
            message=f"Write error: {str(e)}"
        )
    
    reg_error = None
    ok = False
    try:
        ok, reg_error = try_register_node(module_path, class_name, node_id)
        status = RegistrationStatus.OK.value if ok else RegistrationStatus.ERROR.value
    except Exception as e:
        logger.error(f"write_and_register_node_code: register failed: {e}")
        status = RegistrationStatus.ERROR.value
        reg_error = str(e)
    
    try:
        node, err = node_repo.update(
            node_id,
            {
                "registration_status": status,
                "registration_date": datetime.utcnow(),
            },
        )
        if err == "not_found":
            logger.debug("write_and_register_node_code: node %s not in DB, status not persisted", node_id)
    except Exception as e:
        logger.error(f"write_and_register_node_code: DB update failed: {e}")
    
    return SaveCodeResult(
        success=True,
        message="File saved",
        file_path=file_path,
        registration_status=status,
        registration_error=reg_error if not ok else None,
    )


def register_node(
    node_id: str,
    class_name: str,
    module_path: str,
    name: Optional[str] = None,
    created_by: str = "console"
) -> SaveCodeResult:
    """
    Register a node (import module, validate class, create/update DB record).
    
    Args:
        node_id: Node identifier
        class_name: Python class name
        module_path: Full module path
        name: Display name (defaults to node_id titlecased)
        created_by: User who is registering the node
        
    Returns:
        SaveCodeResult with registration status
    """
    from nos.core.engine.plugin_loader import try_register_node
    from .sqlalchemy.node import repository as node_repo
    from .sqlalchemy.node.model import RegistrationStatus
    from ..extensions import db
    
    module_path = _normalize_plugin_module_path(module_path or "", "node")
    # Generate display name if not provided
    if not name:
        name = node_id.replace("_", " ").title()
    
    # Try to register the node
    reg_error = None
    ok = False
    try:
        ok, reg_error = try_register_node(module_path, class_name, node_id)
        status = RegistrationStatus.OK.value if ok else RegistrationStatus.ERROR.value
    except Exception as e:
        logger.error(f"register_node: failed: {e}")
        status = RegistrationStatus.ERROR.value
        reg_error = str(e)
    
    # Create or update DB record
    try:
        node_db = node_repo.get_by_id(node_id)
        if node_db:
            node_repo.update(node_id, {
                "class_name": class_name,
                "module_path": module_path,
                "name": name,
                "registration_status": status,
                "registration_date": datetime.utcnow(),
                "updated_by": created_by,
            })
        else:
            node_repo.create(
                node_id=node_id,
                class_name=class_name,
                module_path=module_path,
                name=name,
                created_by=created_by,
                updated_by=created_by,
                registration_status=status,
                registration_date=datetime.utcnow(),
            )
        db.session.commit()
    except Exception as e:
        db.session.rollback()
        logger.error(f"register_node: DB operation failed: {e}")
        return SaveCodeResult(
            success=False,
            message=f"Database error: {str(e)}"
        )
    
    if ok:
        return SaveCodeResult(
            success=True,
            message=f"Node '{node_id}' registered successfully.",
            registration_status=status
        )
    else:
        return SaveCodeResult(
            success=False,
            message=f"Registration failed: {reg_error}",
            registration_status=status,
            registration_error=reg_error
        )


# =============================================================================
# Workflow Operations
# =============================================================================

def create_workflow(
    workflow_id: str,
    class_name: str,
    module_path: str,
    name: Optional[str] = None
) -> SaveCodeResult:
    """
    Create a new workflow plugin file with template code.
    
    Args:
        workflow_id: Unique workflow identifier
        class_name: Python class name for the workflow
        module_path: Full or relative path (e.g. nos.plugins.workflows.dev.my_workflow or workflows.dev.my_workflow)
        name: Display name (defaults to workflow_id titlecased)
        
    Returns:
        SaveCodeResult with operation status
    """
    normalized_path = _normalize_plugin_module_path(module_path or "", "workflow")
    # Validate and resolve path
    file_path, allowed_dir = resolve_workflow_path(normalized_path)
    if not file_path:
        return SaveCodeResult(
            success=False,
            message="Invalid module_path. Must be under nos.plugins.workflows"
        )
    
    # Check if file already exists
    if os.path.exists(file_path):
        return SaveCodeResult(
            success=False,
            message=f"File already exists: {file_path}"
        )
    
    # Generate name if not provided
    if not name:
        name = workflow_id.replace("_", " ").title()
    
    # Generate content from template (use normalized path)
    content = WORKFLOW_TEMPLATE.format(
        workflow_id=workflow_id,
        class_name=class_name,
        module_path=normalized_path,
        name=name
    )
    
    # Save the file and create DB record
    return save_workflow_code(workflow_id, class_name, normalized_path, content, name=name)


def save_workflow_code(
    workflow_id: str,
    class_name: str,
    module_path: str,
    content: str,
    name: Optional[str] = None
) -> SaveCodeResult:
    """
    Save workflow code to file only (no DB record - use register_workflow for that).
    
    Args:
        workflow_id: Workflow identifier
        class_name: Python class name
        module_path: Full module path
        content: Python source code
        name: Display name (defaults to workflow_id titlecased)
        
    Returns:
        SaveCodeResult with operation status
    """
    # Resolve path
    file_path, allowed_dir = resolve_workflow_path(module_path)
    if not file_path:
        return SaveCodeResult(
            success=False,
            message="Invalid module_path. Must be under nos.plugins.workflows"
        )
    
    # Create directory structure and write file
    try:
        target_dir = os.path.dirname(file_path)
        os.makedirs(target_dir, exist_ok=True)
        
        with open(file_path, "w", encoding="utf-8") as f:
            f.write(content)
    except OSError as e:
        logger.error(f"save_workflow_code: write failed: {e}")
        return SaveCodeResult(
            success=False,
            message=f"Write error: {str(e)}"
        )
    
    return SaveCodeResult(
        success=True,
        message=f"Workflow file created: {file_path}. Use 'reg workflow {workflow_id}' to register.",
        file_path=file_path,
        content=content
    )


def register_workflow(
    workflow_id: str,
    class_name: str,
    module_path: str,
    name: Optional[str] = None,
    created_by: str = "console"
) -> SaveCodeResult:
    """
    Register a workflow (import module, validate class, create/update DB record).
    
    Args:
        workflow_id: Workflow identifier
        class_name: Python class name
        module_path: Full module path
        name: Display name (defaults to workflow_id titlecased)
        created_by: User who is registering the workflow
        
    Returns:
        SaveCodeResult with registration status
    """
    from nos.core.engine.plugin_loader import try_register_workflow
    from .sqlalchemy.workflow import repository as workflow_repo
    from .sqlalchemy.workflow.model import RegistrationStatus
    from ..extensions import db
    
    module_path = _normalize_plugin_module_path(module_path or "", "workflow")
    # Generate display name if not provided
    if not name:
        name = workflow_id.replace("_", " ").title()
    
    # Try to register the workflow
    reg_error = None
    ok = False
    try:
        ok, reg_error = try_register_workflow(module_path, class_name, workflow_id)
        status = RegistrationStatus.OK.value if ok else RegistrationStatus.ERROR.value
    except Exception as e:
        logger.error(f"register_workflow: failed: {e}")
        status = RegistrationStatus.ERROR.value
        reg_error = str(e)
    
    # Create or update DB record
    try:
        wf_db = workflow_repo.get_by_id(workflow_id)
        if wf_db:
            workflow_repo.update(workflow_id, {
                "class_name": class_name,
                "module_path": module_path,
                "name": name,
                "registration_status": status,
                "registration_date": datetime.utcnow(),
                "updated_by": created_by,
            })
        else:
            workflow_repo.create(
                workflow_id=workflow_id,
                class_name=class_name,
                module_path=module_path,
                name=name,
                created_by=created_by,
                updated_by=created_by,
                registration_status=status,
                registration_date=datetime.utcnow(),
            )
        db.session.commit()
    except Exception as e:
        db.session.rollback()
        logger.error(f"register_workflow: DB operation failed: {e}")
        return SaveCodeResult(
            success=False,
            message=f"Database error: {str(e)}"
        )
    
    if ok:
        return SaveCodeResult(
            success=True,
            message=f"Workflow '{workflow_id}' registered successfully.",
            registration_status=status
        )
    else:
        return SaveCodeResult(
            success=False,
            message=f"Registration failed: {reg_error}",
            registration_status=status,
            registration_error=reg_error
        )
